---
meta:
  environment: signalfx-firehose-nozzle-warden

name: signalfx-firehose-nozzle
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
- {name: signalfx-firehose-nozzle, version: '0+dev.1'}

compilation:
  workers: 1
  reuse_compilation_vms: true
  network: signalfx-firehose-nozzle-network
  cloud_properties: {}

networks:
- name: signalfx-firehose-nozzle-network
  subnets:
    - range: 10.244.99.0/30
      reserved:
      - 10.244.99.1
      static: []
      cloud_properties: {}
    - range: 10.244.99.4/30
      reserved:
      - 10.244.99.5
      static: []
      cloud_properties: {}
    - range: 10.244.99.8/30
      reserved:
      - 10.244.99.9
      static: []
      cloud_properties: {}

jobs:
- name: signalfx-firehose-nozzle-main
  instances: 1
  templates:
  - {name: signalfx-firehose-nozzle, release: signalfx-firehose-nozzle}
  resource_pool: signalfx-firehose-nozzle
  networks:
  - name: signalfx-firehose-nozzle-network

resource_pools:
- name: signalfx-firehose-nozzle
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000


properties:
  cf:
    api_url: https://cloudcontroller.bosh-lite.com
    traffic_controller_url: wss://doppler.bosh-lite.com:4443
  uaa:
    url: https://uaa.bosh-lite.com
    username: signalfx-firehose-nozzle
    password: s3cr3t
  nozzle:
    insecure_ssl_skip_verify: true
    subscription_id: signalfx
    deployment: (( meta.environment ))
  signalfx:
    access_token: testing
    ingest_url: https://ingest.signalfx.com

