---
dev_name: signalfx-agent-new
latest_release_filename: "/Users/bk0002/go/src/github.com/signalfx/cloudfoundry-integration/bosh-release/dev_releases/signalfx-agent-new/signalfx-agent-new-0+dev.1.yml"
